// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncdywzcwxvgvpddijonu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZHl3emN3eHZndnBkZGlqb251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTIxNzksImV4cCI6MjA2OTE4ODE3OX0.cgRPy1aNdyoU1D4rPmCYBXtbs4p98d3haYaeC-MHGh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});